name: btob
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.7
  fl_chart: ^0.64.0
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/intro/logo_abii.svg
    - assets/intro/service.gif
    
    - assets/homepage/beer.svg
    - assets/homepage/statistics.svg
    - assets/homepage/shop.svg

    - assets/createdistributor/dai.svg
    - assets/createdistributor/tai.svg
    - assets/createdistributor/wall.svg
    - assets/createdistributor/Biere_Truck.svg
    - assets/createdistributor/cleaner.svg
