name: btob
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/intro/abii-3.svg
    - assets/intro/background2.png
    - assets/intro/background2.png
    - assets/intro/service_avi.avi
    - assets/intro/service_gif.gif
    - assets/intro/service_svg.svg

    - assets/homepage/braintap.svg
    - assets/homepage/donnee.svg
    - assets/homepage/donnee2.svg
    - assets/homepage/shop.svg
